import type { Metadata } from "next";

import "src/sass/main.scss";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "../styles/fonts/DM-Sans/DMSans-VariableFont.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
